### ISSUE TITLE
Output folder of tsc differs when using tsconfig

### ISSUE THREAD

**Issue by mzt** [ivogabe/gulp-typescript#309] opened 2016-03-14 17:11 UTC
**Expected behavior:**
ts files residing in ./app folder should be produced directly in ./build, same as tsc

**Actual behavior:**
gulp-typescript puts them in ./build/app

**Your gulpfile:**
```js
var gulp = require('gulp');
var ts = require('gulp-typescript');
var tsProj = ts.createProject('tsconfig.json');

gulp.task('scripts', () =>
    tsProj.src()
        .pipe(ts(tsProj))
        .js.pipe(gulp.dest('build')));
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "build"
  },
  "exclude": [
    "build",
    "lib",
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}

```

I'm using ts 1.8.7 in both cases.

**Comment by matthiasg** [comment] 2016-03-15 18:08
had the same issue, it works for me when i dont specify `outDir` in the tsconfig.json. gulp-typescript really should just ignore that anyways since the `...pipe(gulp.dest('build'))` would overwrite that anyway. 

Alternatively you can overwrite that from the gulpfile with

`const tsProject = ts.createProject('tsconfig.json',{outDir:undefined});`

**Comment by ivogabe** [comment] 2016-03-16 08:31
This looks like a bug that was fixed in 2.11.0. Are you using the latest version of gulp-typescript? If so, what happens when you downgrade to 2.10.0?

**Comment by mzt** [comment] 2016-03-20 18:36
I tested versions 2.10.0, 2.11.0, 2.12.0, 2.12.1 with ts 1.8.7 and with outDir removed from tsconfig with the same result. I also tested 2.12.1 with ts 1.5.3 and 1.8.9.

My folder structure:
```
+-- app
| `-- *.ts
+-- typings
| `-- ...
+-- tsconfig.json
+-- gulpfile.js
...
```

Another thing, source maps aren't generated when set in tsconfig.

**Comment by ivogabe** [comment] 2016-03-24 15:53
@mzt You must add `gulp-sourcemaps` for source maps, have you tried that?

**Comment by ivogabe** [comment] 2016-03-24 21:12
This looks like a duplicate of the problem mentioned at the bottom of #253, which has just been fixed in the master.

**Closed by ivogabe** 2016-03-24 21:12 UTC
Labels: Bug, Needs More Info
