### ISSUE TITLE
Sourcemaps not being correctly mapped for preprocessed files.

### ISSUE THREAD

**Issue by techmatt101** [ivogabe/gulp-typescript#460] opened 2016-11-19 19:54 UTC
Given TS files after being preprocessed by [gulp-concat](https://github.com/contra/gulp-concat) or anything equivalent, the sourcesContent on sourcemaps generated result to null and sources listed are not the original src files. Below is my current setup.

**Example Setup:**
```
└── src/
   ├── apple.ts
   └── banana.ts
```
```javascript
gulp.task('default', function () {
  return gulp.src('src/**/*.ts')
    .pipe(sourcemaps.init())
    .pipe(concat('all.ts'))
    .pipe(typescript())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('build'));
});
```

When opening `build/all.js` using [source-map-visualization](http://sokra.github.io/source-map-visualization/) it fails to load. `Error: Source 'all.ts' missing.`

**Expected source map output:**
``` json
{"version":3,"sources":["apple.ts","banana.ts"],"names":[],"mappings":"AAAA;IAAA;IAAA,CAAA;IAAA,YAAA;AAAA,CAAA,IAAA;ACAA;IAAA;IAAA,CAAA;IAAA,aAAA;AAAA,CAAA,IAAA","file":"all.js","sourcesContent":["class Apple {}","class Banana {}"]}
```

**Actual source map output:**
``` json
{"version":3,"sources":["all.ts"],"names":[],"mappings":"AAAA;IAAA;IAAa,CAAC;IAAD,YAAC;AAAD,CAAb,AAAc,IAAA;AACd;IAAA;IAAc,CAAC;IAAD,aAAC;AAAD,CAAd,AAAe,IAAA","file":"all.js","sourcesContent":[null]}
```

**Comment by techmatt101** [comment] 2016-11-19 20:03
I've started debugging through the code looks like the issue is related to the file path being absolute and changing the file to a relative path seems to fix the issue.

**Problem Code:** [output.ts@83](https://github.com/ivogabe/gulp-typescript/blob/master/lib/output.ts#L83)
```typescript
// sourceFile.fileNameOriginal = "C:\Users\Matt\Desktop\test\src\all.ts";
// sourceFile.gulp.base = "C:\Users\Matt\Desktop\test\src\";
generator.applySourceMap(consumer, sourceFile.fileNameOriginal, sourceFile.gulp.base);
```
**Proposed Solution:**
```typescript
generator.applySourceMap(consumer, path.relative(sourceFile.gulp.base, sourceFile.fileNameOriginal), sourceFile.gulp.base);
```

**Optional Solution:**
[sourceFile and sourceMapPath are optional parameters](https://github.com/mozilla/source-map#sourcemapgeneratorprototypeapplysourcemapsourcemapconsumer-sourcefile-sourcemappath) but involves reverting a code change from [#6372612](https://github.com/ivogabe/gulp-typescript/commit/6372612f981c50bc0cc3d291ec152fd06075351d) commit (Fix issues with output paths).
```typescript
generator.applySourceMap(consumer);
```

Any thoughts? Will this have any negative repercussion? All tests still pass after making the change.

**Comment by ivogabe** [comment] 2016-11-21 19:52
Thanks for reporting and investigating. I think that your proposed fix is the desired fix, though I would need to do some testing. The optional solution does not work well, the issue is that all paths (involved with source maps) are relative, but relative to different directories. Can you create a pull request with your proposed solution? Then I'll do some testing with it.

**Comment by techmatt101** [comment] 2016-11-30 18:48
Just created a pull request for my "Optional/Second Solution". The reason for not going with my "Proposed Solution" is because I wasn't able to test using absolute paths as the expected result would be confined to my dev environment location ("C:\Users\Matt...."). _Now thinking about it I could of used something like [gulp-rename](https://github.com/hparra/gulp-rename) to work around the issue maybe? :/_

I'm still not sure if it would be a problem, could you possibly have a look over it let me know what issue it causes so I can get a better understating. Might even be worth us adding a test round these problem scenarios.

**Comment by ivogabe** [comment] 2016-11-30 19:16
Thanks for the PR. The test case is a good addition to the test suite. I'm afraid that it might break some other scenario's, but I'll investigate that. I have my mind on other things now but I hope to do that this weekend. I'll try to construct a test case that demonstrates such a scenario.

Absolute paths should not be a problem since gulp-sourcemaps' documentation states that the paths in the sourcemap should be relative.

**Comment by giggio** [comment] 2016-12-26 19:27
I can't use gulp-typescript until this issue is solved. I am reverting back to gulp-exec or something like that.

**Comment by ivogabe** [comment] 2016-12-27 12:25
Fixed in #465

**Closed by ivogabe** 2016-12-27 12:25 UTC

**Comment by giggio** [comment] 2017-01-02 16:43
@ivogabe any idea of when this will make to a release?

**Comment by ivogabe** [comment] 2017-01-06 13:47
@giggio I want to go through some issues today and hope to release it today too.
