### ISSUE TITLE
Wrong `source` in sourcemap, do I need to create a pull request?

### ISSUE THREAD

**Issue by chenzhutian** [ivogabe/gulp-typescript#432] opened 2016-10-03 06:51 UTC
**Node:v6.0**
**Gulp-typescript:v3.0**
**OS: win10**

Suppose I have a `.ts` file in the folder `src/foo/`.
```
src/
|-foo/
|--index.ts
```
After compiling, I can get the js file in `dist` folder with correct structure.
```
dist/
|-foo/
|--index.js
|--index.js.map
```
However, the content in sourcemap is wrong.

**Expected behavior:**
```map
{... "sources":["foo/index.ts"]...}
```

**Actual behavior:**
```map
{... "sources":["foo/foo/index.ts"]...}
```

**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
gulp.task('transpiler', () => {
    console.log('transipiler');
    return tsProject.src() //gulp.src(['./src/**/*.ts', './typings/**/*.d.ts'], { base: './src' })
        .pipe(sourcemaps.init())
        .pipe(tsProject())
        .pipe(sourcemaps.write('./', {
            includeContent: false,
            sourceRoot: file => `${'../'.repeat(file.relative.split(path.sep).length)}src`
        }))
        .pipe(gulp.dest('dist'));
})
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compilerOptions": {
        "target": "es6",
        "outDir": "dist",
        "module": "commonjs",
        "sourceMap": true,
        "preserveConstEnums": true,
        "rootDir": "src",
        "sourceRoot": "dist",
        "declaration": true,
        "baseUrl": ".",
        "paths": {
            "*": [
                "*",
                "src/types/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "dist",
        ".vscode"
    ]
}
```

**Code**
After digging into the code of `gulp-typescript` and `gulp-sourcemap`, I find out that the problem maybe due to this part of code in [`gulp-typescript/lib/output.ts`](https://github.com/ivogabe/gulp-typescript/blob/master/lib/output.ts#L59-L62):
```typescript
const directory = path.dirname(output.path);
// gulp-sourcemaps docs:
// paths in the generated source map (`file` and `sources`) are relative to `file.base` (e.g. use `file.relative`).
map.file = output.relative;
map.sources = map.sources.map(relativeToOutput);
.
.
.
function relativeToOutput(fileName: string) {
    const absolute = path.resolve(directory, fileName.replace(/\\/g, '/'));
    return path.relative(output.base, absolute);
}
```
The `output.path` is something like `root/dist/foo/index.js`, therefore the  `directory` will be `root/dist/foo`.  However, the path in `map.sources` is `foo/index.ts`, which is generated by `gulp-sourcemap`, relative to `file.base` (e.g. `src/`).
So the variable `absolute` in `function relativeToOutput` will be `root/dist/foo/foo/index.ts`. Then the bug happens.

Do I miss something? Or this is actually a bug in `gulp-typescript@v3`

**Comment by ivogabe** [comment] 2016-10-03 16:46
Thanks for reporting. I tried to reproduce it, but I got `"sources":["../src/foo/index.ts"]`; I couldn't reproduce it. Could you send your project or create a minimal reproduction of the issue? You can upload it as a zip-file here on GitHub or mail it to me if it's private.

**Comment by unhealthy** [comment] 2016-10-05 04:24
Sorry for the late reply. You can clone [this repository](https://github.com/unhealthy/for-debugging-gulp-typescript.git) to try to reproduce. 
Thanks.

**Comment by ivogabe** [comment] 2016-10-08 19:43
Strange, I get `"sources":["middlewares/deeper/middlewares/deeper/index.ts"]` (and similar results for other files), tested on Windows and Mac. Could you try to remove `node_modules` and run `npm install` again?

**Comment by chenzhutian** [comment] 2016-10-09 04:15
yes I get this result `"sources":["middlewares/deeper/middlewares/deeper/index.ts"]` also. But it's wrong, right? The correct path should be `"sources":["/middlewares/deeper/index.ts"]`.

I find out that the problem maybe due to this part of code in [`gulp-typescript/lib/output.ts`](https://github.com/ivogabe/gulp-typescript/blob/master/lib/output.ts#L59-L62):
```typescript
const directory = path.dirname(output.path);
// gulp-sourcemaps docs:
// paths in the generated source map (`file` and `sources`) are relative to `file.base` (e.g. use `file.relative`).
map.file = output.relative;
map.sources = map.sources.map(relativeToOutput);
.
.
.
function relativeToOutput(fileName: string) {
    const absolute = path.resolve(directory, fileName.replace(/\\/g, '/'));
    return path.relative(output.base, absolute);
}
```
The `output.path` is something like `root/dist/foo/index.js`, therefore the  `directory` will be `root/dist/foo`.  However, the path in `map.sources` is `foo/index.ts`, which is generated by `gulp-sourcemap`, relative to `file.base` (e.g. `src/`).
So the variable `absolute` in `function relativeToOutput` will be `root/dist/foo/foo/index.ts`. Then the bug happens.

**Comment by ivogabe** [comment] 2016-10-09 08:36
Oops, you're correct. It appears that it does work correctly when you remove the `sourceRoot` option. This option should be ignored by gulp-typescript, since source map options should be passed to gulp-sourcemaps. So marking this as a bug, but you can already remove the `sourceRoot` option yourself.

**Comment by chenzhutian** [comment] 2016-10-09 09:40
cool, it works right when the `sourceRoot` is removed from `tsconfig.json`.

**Closed** 2016-10-22 20:25 UTC
Labels: Bug
