### ISSUE TITLE
Using outDir causes nothing to compile

### ISSUE THREAD

**Issue by Kequc** [ivogabe/gulp-typescript#305] opened 2016-03-08 15:00 UTC
The problem I'm trying to resolve is that my references are pointing to the wrong place when I use the declaration: true option.

``` javascript
  var tsResult = gulp.src('./src/app.ts')
    .pipe(ts({
      noImplicitAny: true,
      declaration: true,
      target: 'ES5',
      removeComments: true,
      outFile: 'app.js'
    }));
  return merge([
    tsResult.dts
      .pipe(gulp.dest('./build')),
    tsResult.js
      .pipe(gulp.dest('./build'))
      .pipe(uglify())
      .pipe(gulp.dest('./lib/release'))
  ]);
```

Original file includes: 

`/// <reference path="../typings/browser/ambient/waa/waa.d.ts" />`

Compiled looks like:

`/// <reference path="typings/browser/ambient/waa/waa.d.ts" />`

If I add the outDir option as is listed at the top of the readme, then nothing gets compiled at all.

**Comment by Kequc** [comment] 2016-03-08 15:08
For the time being I am using the following workaround, using the gulp-replace package:

```javascript
    tsResult.dts
      .pipe(replace('reference path="', 'reference path="../'))
      .pipe(gulp.dest('./build')),
```

**Comment by ivogabe** [comment] 2016-03-09 17:00
The cause is probably that gulp-typescript doesn't expect both the `outFile` and `outDir` settings, though this should be working.

**Comment by mko** [comment] 2016-03-21 18:25
I can confirm this bug is also occurring for me (without the `outFile` setting being set). I'm not sure when `outDir` last worked, but I can confirm manual `tsc` compilation works but `gulp-typescript` results in no files being written.

**Comment by ivogabe** [comment] 2016-03-21 20:49
@mko Can you share your gulpfile, tsconfig.json and directory structure?

**Comment by mko** [comment] 2016-03-21 21:30
Sure. I'm working on a sample project for isolating the build environment issues right now, so it's already "anonymized" as it were: https://gist.github.com/mko/cfeb9a82fb8dd563ff4a

**Comment by mko** [comment] 2016-03-21 21:35
Note: I just realized that in that version, I was attempting to pipe it directly to a directory specified by string (the same string as the `outDir` in my `tsconfig.json`). I've tried it referencing the `outDir` value directly (i.e. `tsProject.config.compilerOptions.outDir`) as well as not referencing it at all and expecting the `gulp-typescript` plugin to do it for me, but it hasn't worked on any of the variations.

**Comment by mko** [comment] 2016-03-21 21:36
It should also be noted that I'm using a nightly version of TypeScript, as I need the new Path Mapping functionality offered in TypeScript `1.9.x`.

**Comment by mko** [comment] 2016-03-21 22:20
![screen shot 2016-03-21 at 3 17 11 pm](https://cloud.githubusercontent.com/assets/85261/13936022/12c8022e-ef78-11e5-9615-31e05f7adca1.png)

I threw `gulp-debug` in there to get more info. Looks like it's properly parsing all of the source files, but the resulting `tsResult` stream is empty. I also thought maybe it was a scoping issue, but I tested it more tightly scoped and it didn't change anything.

**Comment by mko** [comment] 2016-03-21 22:35
I was able to get it to transpile the files by not using a `tsProject`, but it's as if it's validating the TypeScript files using a different version of TypeScript than the one specified in my options object with `typescript: require('typescript')`. It errors out on the path mapping process like so:

![screen shot 2016-03-21 at 3 35 08 pm](https://cloud.githubusercontent.com/assets/85261/13936380/8eca2422-ef7a-11e5-872a-d464ff97eaa6.png)

**Comment by mko** [comment] 2016-03-21 22:37
It may be that [this PR](https://github.com/ivogabe/gulp-typescript/pull/283) and Issue #299 may be related as well.

Path mapping is an important feature (and likely will be the default for most developers), but I understand it's bleeding edge, so support may be spotty.

**Comment by christiandreher** [comment] 2016-05-16 20:32
This issue is dated from march 8. Are there any updates or workarounds? Because I am facing the very same issue right now, perfectly described by @mko. I have tried any combination for the paths, but it just wont work. `tsc` compiles everything just fine.
It is very annoying for me, since I really need the `paths` feature of TypeScript 1.9.x.
If you think that additional information about my setup is helpful, please let me know, I will happily provide anything

**Comment by ivogabe** [comment] 2016-05-17 16:05
@christiandreher Path mapping should be working with a recent version of gulp-typescript and a nightly build of TypeScript. If not, could you create a new issue with your gulpfile and tsconfig file?

**Comment by ivogabe** [comment] 2016-05-17 16:16
@mko Could you try the latest version? Some of your problems are now fixed probably.

**Comment by christiandreher** [comment] 2016-05-17 16:19
@ivogabe Before I open a new Issue, could you verify that I am up-to-date? I am using typescript@1.9.0-dev.20160517-1.0 with gulp-typescript@2.13.4. As far as I know, these are the current versions.

**Comment by ivogabe** [comment] 2016-05-17 16:20
@christiandreher Yes, you're up to date.

**Comment by christiandreher** [comment] 2016-05-17 16:21
Thank you, I will open a issue then

**Comment by ivogabe** [comment] 2016-12-12 11:37
This seems to be solved in the current version of gulp-typescript.

**Closed by ivogabe** 2016-12-12 11:37 UTC
Labels: Bug
