### ISSUE TITLE
gulp failed on 2.4.1

### ISSUE THREAD

**Issue by ngbinh** [ivogabe/gulp-typescript#64] opened 2015-01-28 04:29 UTC
version: 
```
    "typescript": "^1.4.1",
    "gulp-typescript": "2.4.1",
```

problem:
```
Error: ENOENT, no such file or directory 'node_modules/gulp-typescript/node_modules/typescript/bin/lib.d.ts'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Function.Host.initLibDefault (node_modules/gulp-typescript/release/host.js:14:26)
    at Object.<anonymous> (node_modules/gulp-typescript/release/host.js:79:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

looks like gulp-typescript doesn't look at the right instance of typescript.

**Comment by whitneyit** [comment] 2015-01-29 00:35
@ivogabe This is another duplicate of #59. Can we get a release pushed to npm please.

**Comment by ivogabe** [comment] 2015-01-31 08:14
Duplicate indeed. New version is on npm

**Closed by ivogabe** 2015-01-31 08:14 UTC
