### ISSUE TITLE
rootDir gets ignored when using tsconfig.json

### ISSUE THREAD

**Issue by luho383** [ivogabe/gulp-typescript#427] opened 2016-09-29 19:14 UTC
Does gulp-typescript ignore rootDir settings when using tsconfig.json??

when compiling with this plugin the result of the module name is as following:

System.register("source/ts/main"....

but when I use tsc, I get this:
System.register("main" ...

which is what I wanted...

**tsconfig.json**
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "emitDecoratorMetadata": false,
    "experimentalDecorators": false,
    "removeComments": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitAny": false,
    "noImplicitUseStrict": false,
    "declaration": true,
    "pretty": true,
    "rootDir": "source/ts",
    "outFile": "built/js/example.js"
  },
  "exclude": [
    "built",
    "node_modules"
  ],
  "typingOptions": {
    "enableAutoDiscovery": true
  },
  "enableAutoDiscoveryDefinition": true
}

**Comment by ivogabe** [comment] 2016-10-01 13:02
Can you share your gulpfile?

**Comment by remojansen** [comment] 2016-10-02 15:26
Hi @ivogabe,

I just upgraded a few projects to 3.0.2 and I'm getting this error as well. You can find a few broken builds as examples at:

- https://travis-ci.org/inversify/inversify-restify-utils/jobs/164438521
- https://travis-ci.org/inversify/inversify-express-utils/jobs/164437307
- https://travis-ci.org/inversify/inversify-logger-middleware/jobs/164437200

Thanks!

**Comment by ivogabe** [comment] 2016-10-03 17:34
Hi Remo, I think that this is not really related to this issue. This behaviour has changed in version 3, and it was an intentional change. The new rule is that if the `rootDir` option is not set, it will be set to the base path of the input files. Basically, that's the part where the glob starts in `gulp.src`. In the failing build of inversify-restify-utils, that would be `test`. The problem is then that the compiler finds source files outside of the rootDir, namely inside the `src` folder. You can fix this by explicitly setting the `rootDir` option to `./`. See also http://dev.ivogabe.com/gulp-typescript-3/, seventh point.

**Comment by luho383** [comment] 2016-10-12 19:46
Hi, had to clean it up a bit:

var pathFS = require('path');

/** base files (framework) */
var tsFiles = {
    typings: [
        'Typings/Framework.d.ts',
        'Typings/globals/es6-promise/index.d.ts'
    ],
    framework: [
        'Framework/Globals.ts',
        'Framework/Polyfills.ts',
        'Framework/Core/Events.ts',
        'Framework/Core/Tuple.ts',
        'Framework/Build.ts',
        'Framework/Platform.ts',
        'Framework/Debug.ts',
        'Framework/IO/StorageProvider.ts',
        'Framework/IO/Notifier.ts',
        'Framework/IO/LoadingManager.ts',
        'Framework/IO/ModelLoader.ts',
        'Framework/IO/ImageLoader.ts',
        'Framework/AssetManager.ts',
        'Framework/Shaders.ts',
        'Framework/MaterialLibrary.ts',
        'Framework/Render.ts',
        'Framework/Localization.ts',
        'Framework/Model.ts',
        'Framework/Input.ts',
        'Framework/World.ts',
        'Framework/Component.ts',
        'Framework/Components/MeshComponent.ts',
        'Framework/Components/HemisphereLightComponent.ts',
        'Framework/Components/PointLightComponent.ts',
        'Framework/Components/DirectionalLightComponent.ts',
        'Framework/App.ts',
        'Framework/CameraControl.ts',

        'Framework/Shaders/Unlit.ts',
        'Framework/Shaders/Basic.ts',
        'Framework/Shaders/Standard.ts',
        'Framework/Shaders/CustomDepth.ts',

        'Framework/Anim/PathAnimation.ts',
        'Framework/Anim/ValueAnimation.ts',

        'Framework/Framework.ts'
	]
};

/** base pathes */
var tsPaths = {
    source: 'source/',
    deploy: 'dist',
}

var paths = tsPaths
var files = tsFiles;
var bundleFile = "test";
var tscConfig = "tsconfig.json";

var customProps = {
    typescript: plugins.tsc,
};

if(bundleFile) {
    // custom bundle file output
    customProps.outFile = bundleFile;
}

var tsProject = null;

// own tscconfig file...
tsProject = plugins.typescript.createProject(tscConfig, customProps);

var fileStream = new plugins.streamqueue({ objectMode: true });

for(var entry in files) {
    fileStream = fileStream.queue(gulp.src(files[entry], {cwd: pathFS.resolve(paths.source), base: paths.source}));
}
var isDev = true; 
var writeSourceMaps = true;

fileStream.done();

var tscStream = plugins.typescript(tsProject, undefined, plugins.typescript.reporter.fullReporter())

return plugins.mergeStream(fileStream
    .pipe(plugins.ifElse(writeSourceMaps, () => plugins.sourcemaps.init({loadMaps: true, debug:true})))
    .pipe(tscStream).js
    .pipe(plugins.ifElse(writeSourceMaps, () => plugins.sourcemaps.write({ includeContent: true }))) 
    .pipe(gulp.dest(paths.deploy))
    ,
    //dts stream
    fileStream.pipe(tscStream).dts
    .pipe(gulp.dest(paths.deploy))
);

}

this is the pre 3.0 gulp file, for 3.0 I only changed the api changes, but nothing on gulp.src or the stream queue.

**Comment by wmathes** [comment] 2016-10-24 03:52
Hmm there seems to be a general issue with setting the rootDir as it simply doesn't work when providing multiple values via a fileGlobs array.

### explanation
i have a `/src` and a `/test` folder which are provided as `gulp.src(["src/**/*.ts", "test/**/*.ts"])`. Now i would assume that gulp-typescript will implicitly set the rootDir to "./" putting my files in respective subfolders, but it doesn't. It just merges the output into the gulp.dest() folder.

Overriding the value by setting it "./" by hand has no effect. I even tried using my full system path without success. 

What actually does work though (and that was discovered by accident), is setting a rootDir which is wrong and just addresses the first array value. In my case setting it to "/wrong" will actually do what i want it to do (probably by accidentally breaking something :P). There are errors popping up for all files in /test, but he's compiling all of them anyway (including sourcemaps/declarations) and putting them into their own respective folders.

### repo
I created a [tiny repo](https://github.com/wmathes/gulp-ts-rootdir-issue) to highlight the issue. 
- `git clone https://github.com/wmathes/gulp-ts-rootdir-issue`
- `npm install`
- `npm run compile`

In the `/build` folder both original directories are merged loosing their /src and /test directories. You can break-fix this in the above described way. Toggle gulpfile.js:13&14 to see the effect. 

Is this intended? Maybe i just misunderstand the concept of rootDir. ^^
Should i open up a separate issue for this?

**Comment by ivogabe** [comment] 2016-10-24 05:06
That's how gulp works. This is related to the base path that gulp calculates, not the value of `rootDir`. When you write `gulp.src(["src/**/*.ts", "test/**/*.ts"])`, gulp will set the base path of those files to `src` or `test`. `gulp.dest` will write those files to the disk, based on their relative paths, relative to the base path. For instance, if you have some file `src/a/b.ts`, its base path is `src`, so its relative path is `a/b.ts`.

By default, the base path is the position where the glob starts. But, you can also specify if yourself, like `gulp.src(["src/**/*.ts", "test/**/*.ts"], { base: "./" })`. That should solve your issue.

**Closed** 2016-12-11 19:07 UTC
