### ISSUE TITLE
Using two projects in the same gulp task throws "Could not find input file"

### ISSUE THREAD

**Issue by cristi-badila** [ivogabe/gulp-typescript#357] opened 2016-05-27 16:41 UTC
**Expected behavior:**
Using two projects in the same gulp task should not through exceptions
**Actual behavior:**
Using two projects in the same gulp task throws `Could not find input file \________________empty.ts. This is probably an issue of gulp-typescript.`. In my solution I have a watch task that monitors 2 projects (PorjectA and ProjectB). When changes occur sequentially for ProjectA, builds are triggered for that project and everything works fine. However when a change occurs first in ProjectA and the next change occurs in ProjectB, the first build works but the second one throws the above exception.
**Your gulpfile:**

_Include your gulpfile, or only the related task (with `ts.createProject`)._

``` javascript
var appProject = plugins.typescript.createProject(paths.tsConfig);
var testProject = plugins.typescript.createProject(paths.testsTSConfig);

function transpileTS(filesGlob, destDir, project) {
    return gulp.src(filesGlob)
        .pipe(plugins.typescript(project))
        .pipe(gulp.dest(destDir));
}

function transpileApp() {
    return transpileTS(paths.ts, paths.karmaDir, appProject);
}

function transpileTests() {
    return transpileTS(paths.unitTests, paths.karmaDir, testProject);
}

function transpileLive() {
    gulp.watch(paths.ts, gulp.series(transpileApp));
    gulp.watch(paths.unitTests, gulp.series(transpileTests));
}

gulp.task('specsLive', transpileLive);
```

**tsconfig.json**

_Include your tsconfig, if related to this issue._

``` json

```

**Code**

_Include your TypeScript code, if necessary._

``` typescript

```

**Comment by ivogabe** [comment] 2016-05-27 18:35
Looks like a duplicate of #342, which has been fixed in the latest release. Can you try the latest release (2.13.5)?

**Comment by cristi-badila** [comment] 2016-05-30 06:31
@ivogabe I thought the same thing and made sure to be on the latest version (2.13.5) before opening up this issue.

**Comment by keathmilligan** [comment] 2016-06-14 16:03
I still get this issue intermittently on 2.13.6

**Comment by ivogabe** [comment] 2016-09-23 12:26
This should not happen any more in version 3.0, can everyone check that?

**Comment by symbyte** [comment] 2016-09-23 13:01
Working great for me, nice work @ivogabe!

**Closed** 2016-12-11 19:02 UTC
