### ISSUE TITLE
Allow comments in tsconfig.json

### ISSUE THREAD

**Issue by RehanSaeed** [ivogabe/gulp-typescript#210] opened 2015-09-26 11:05 UTC
Comments don't seem to be allowed in the tsconfig.json file. See [this](http://blog.getify.com/json-comments/) article for why it is ok according to Douglas Crockford to add them to json config files.

This is the error I get when adding comments to my tsconfig.json file:

```
var typescript = require("gulp-typescript");
var typeScriptProject = ts.createProject("tsconfig.json");
```

```
Process terminated with code 0.
> cmd.exe /c gulp -b "C:\Test\WebApplication1\WebApplication1" --color --gulpfile "C:\Test\WebApplication1\WebApplication1\Gulpfile.js" build-js
SyntaxError: Unexpected token /
    at Object.parse (native)
    at Function.createProject (C:\Test\WebApplication1\WebApplication1\node_modules\gulp-typescript\release\main.js:195:40)
    at Object.<anonymous> (C:\Test\WebApplication1\WebApplication1\Gulpfile.js:68:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (C:\Test\WebApplication1\WebApplication1\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Test\WebApplication1\WebApplication1\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Test\WebApplication1\WebApplication1\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
Process terminated with code 8.
    at Liftoff.<anonymous> (C:\Test\WebApplication1\WebApplication1\node_modules\gulp\node_modules\liftoff\index.js:185:9)
    at C:\Test\WebApplication1\WebApplication1\node_modules\gulp\node_modules\liftoff\index.js:159:9
    at C:\Test\WebApplication1\WebApplication1\node_modules\gulp\node_modules\v8flags\index.js:99:14
    at C:\Test\WebApplication1\WebApplication1\node_modules\gulp\node_modules\v8flags\index.js:38:7
    at process._tickCallback (node.js:419:13)
```

**Comment by ivogabe** [comment] 2015-09-26 15:22
I think this should be implemented in TypeScript first. If this would be implemented in gulp-typescript only,  you cannot use the tsconfig file in VSCode for instance, whereas this configuration file was designed to be a universal config file. I'm not sure whether such issue has already been reported at the TypeScript repository. If not, you can report an issue there.

**Comment by RehanSaeed** [comment] 2015-09-26 15:51
@ivogabe Thanks, I've raised a new issue on the official TypeScript project. Let's see what happens.

**Comment by jods4** [comment] 2016-02-24 23:07
@ivogabe Time to reopen this issue I think!
TS 1.8 now includes support for comments in tsconfig.json.
Unfortunately we can't use them in combination with gulp-typescript because it does its own parsing based on `JSON.parse`, which does not support comments.

**Comment by aliok** [comment] 2016-02-25 23:36
:+1: 
I got the same problem. Running `tsc` works perfect with a commented *tsconfig.json* but not with *gulp-typescript*.

**Comment by jods4** [comment] 2016-02-25 23:52
Most robust approach would be to call `parseConfigFileTextToJson()` if possible, I see it's exported (from the module it's defined in, at least). 
Otherwise probably copy their code?

It's not as intuitive as you'd think, for instance it supports `#` as line comments.

**Comment by aliok** [comment] 2016-02-26 00:22
Well, that solution I posted is changed a lot by the TS people while merging into TS.

This is their merged solution:
https://github.com/Microsoft/TypeScript/commit/3e631449a184ade110346623f93aeebabbef93f9

See the discussion:
https://github.com/Microsoft/TypeScript/pull/5450

**Closed** 2016-02-26 08:58 UTC
Labels: Bug, Suggestion

**Comment by aliok** [comment] 2016-02-26 12:42
Thanks for fixing the issue. Any plans about release?

**Comment by ivogabe** [comment] 2016-02-26 13:09
Probably next week

**Comment by RehanSaeed** [comment] 2016-03-07 20:17
@ivogabe Has this feature made it out yet?

**Comment by ivogabe** [comment] 2016-03-07 20:24
It has been added in v2.12.1

**Comment by aliok** [comment] 2016-03-07 23:14
@ivogabe Great!
Confirmed, it works.
