### ISSUE TITLE
Cannot read property 'gulp' of undefined

### ISSUE THREAD

**Issue by nevcos** [ivogabe/gulp-typescript#118] opened 2015-05-12 16:20 UTC
After updating to version 2.7.3 (from 2.6.x):

```
npm install
npm WARN prefer global typescript@1.4.1 should be installed with -g
gulp-typescript@2.7.3 node_modules\gulp-typescript
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── source-map@0.4.2 (amdefine@0.1.0)
├── gulp-util@3.0.4 (beeper@1.0.0, object-assign@2.0.0, array-differ@1.0.0, ar
ray-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash.
_reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.4.6, chalk@1.0.0,
lodash.template@3.5.1, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@1.0.0 (merge-stream@0.1.7, object-assign@2.0.0, graceful-fs@3.0.6
, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.0, duplexify@3.3.0, glob-watcher@0.
0.8, glob-stream@4.1.1)
```

It's giving the following error:

```
app\node_modules\gulp-typescript\release\output.js:63
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
    at Output.addOrMergeFile (app\node_modules\gulp-typescript\release\output.js:63:51)
    at Output.write (app\node_modules\gulp-typescript\release\output.js:35:14)
    at ProjectCompiler.inputDone (app\node_modules\gulp-typescript\release\compiler.js:59:33)
    at CompileStream.end (app\node_modules\gulp-typescript\release\main.js:52:31)
    at DestroyableTransform.onend (app\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at app\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
```

Have deleted all cache, deleted "node_modules" directory, unistalled/deleted all nodejs / npm files and the problem persists.

Downgrading to gulp-typescript version 2.5 or 2.6, solves the problem.
I'm using NPM 2.7.4, Node 0.12.2 and Windows 7 Professional (6.1 Build 7601; SP1).

Thanks!

**Comment by ivogabe** [comment] 2015-05-12 16:22
Have you tried using the master of GitHub? Have you tried using TypeScript 1.5 (see readme of gulp-typescript how to do that)?

**Comment by nevcos** [comment] 2015-05-12 16:32
Tested only version 2.7.3, not master.
Tested with TypeScript to 1.5-alpha and it worked flawlessly, thanks!

**Comment by nevcos** [comment] 2015-05-12 16:35
Tested only with version 2.7.3, not with master.
Tested using TypeScript to 1.5-alpha but the problem persists.

**Comment by ivogabe** [comment] 2015-05-12 16:38
Looks like a duplicate of #117, which is fixed in the master.

**Comment by nevcos** [comment] 2015-05-12 16:56
Tested using master - ```"gulp-typescript": "ivogabe/gulp-typescript"``` - but the problem persists.

**Comment by ivogabe** [comment] 2015-05-12 17:36
Can you post more about your project, such as gulpfile and file structure? Also, what happens when you turn noExternalResolve on?

**Comment by randallmeeker** [comment] 2015-05-12 18:13
same problem
Using latest gulp-typescript and typescript 
On Windows 7 machine. 
Tried with ```noExernalResolve:true```

**Comment by ivogabe** [comment] 2015-05-12 18:23
@randallmeeker Do you get different errors when `noExternalResolve` is on? Can you post more about your project?

**Comment by randallmeeker** [comment] 2015-05-12 18:33
correct, I'm only attempting to run the single gulp task. I get the exact error as @nevcos 
```
ts = require('gulp-typescript'),
var tsProject = ts.createProject({
   noExternalResolve: true,

});
gulp.task('build-ts', function(){
	tsResult = gulp.src(paths.ts)
		.pipe(ts(tsProject));
    return tsResult.js.pipe(gulp.dest(pubPath));
});
```

**Comment by ivogabe** [comment] 2015-05-12 18:38
@randallmeeker Can you post more about your project structure? Or can you create a minimal example that reproduces it?

**Comment by randallmeeker** [comment] 2015-05-12 19:14
Ya, I'm attempting to figure this out. A fresh build in a new directory works fine. If I copy gulp files between the fresh one and the old I get the error. So I assume it has to be a stale library/package. I remove gulp, gulp-typescript and typescript. Clean the cache and npm install them all again and still get the error. I have matched versions across both directories and am at a loss. At this point however, it does not appear to be an issue directly with gulp-typescript but any help into what in my project structure could be causing this would be appreciated. If I find it I'll post back.

**Comment by ivogabe** [comment] 2015-05-12 19:20
Can you retest it with the master? I've added better error handling so if you're still getting the error you will get a nicer error with better debug information that might help find the cause.

**Comment by randallmeeker** [comment] 2015-05-12 19:36
new error after update from master

```
 Error: Invalid glob argument: undefined
    at Gulp.src (c:\inetpub\wwwroot\_x-schedule\node_modules\gulp\node_modules\vinyl-fs\lib\src\index.js:20:11)
    at Gulp.reloadclient (c:\inetpub\wwwroot\_x-schedule\Gulpfile.js:85:18)
    at module.exports (c:\inetpub\wwwroot\_x-schedule\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\inetpub\wwwroot\_x-schedule\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\inetpub\wwwroot\_x-schedule\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (c:\inetpub\wwwroot\_x-schedule\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Randall\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

**Comment by ivogabe** [comment] 2015-05-12 19:38
@randallmeeker That error has nothing to do with gulp-typescript, that means something in your `gulp.src(...)` call isn't right.

**Comment by randallmeeker** [comment] 2015-05-12 19:48
ya, right. My bad. I'm deleting that so as to not confuse this thread.

The new error, which I'm reading and attempting to . . . . ya figure out. I am use the latest typescript . . . 

```
The common source directory of the source files isn't equal to the common base directory of the input files. That isn't supported using the version of TypeScript currently used. Use a newer version of TypeScript instead or have the common source directory point to the common base directory.
```

**Comment by ivogabe** [comment] 2015-05-12 19:55
Let me give an example of what's happening:
In your gulp file you have something like `gulp.src('foo/**/**.ts')`. That means the base path of these files is `foo`. The TypeScript compiler finds out that all files are placed in the directory `foo/bar`. As of TypeScript 1.5, the compiler will use `foo` as common source directory, but if you're using 1.4 typescript will use the wrong common source directory. That will cause the build to fail. There are 3 options:

1. Change your gulp.src call to `gulp.src('foo/bar/**/**.ts')`.
2. Use TypeScript 1.5 beta
3. Add a source file in the directory `foo`

**Comment by randallmeeker** [comment] 2015-05-12 19:57
I am using TypeScript 1.5 beta???

and thanks for the hand holding on this

**Comment by ivogabe** [comment] 2015-05-12 19:59
Then you shouldn't get that error. Can you create a minimal example that reproduces your problem? I really cannot see what's going wrong this way. Using the same gulp file & replicating the file structure will probably be enough to get the same error.

**Comment by randallmeeker** [comment] 2015-05-12 20:26
You describe the problem perfectly, because the hack fix was to place a .ts file in the root directory. That fixed it. And my fresh directory broke by replicating the directory structure.

Here is the minimal that will reproduce this error on my machine

https://github.com/randallmeeker/gulp-typescript-test

**Comment by ivogabe** [comment] 2015-05-12 20:28
Nice to hear it's solved. Regarding to the typescript version, you should change your gulp file like this:
```javascript
var tsProject = ts.createProject({
   noExternalResolve: true,
   target : 'ES5',
   typescript: require('typescript')
});
```
The line where typescript is required is important, if you don't add that file you'll still be using TS 1.4

@nevcos Can you retest with the current master? If that still fails, can you create an example that reproduces this issue?

**Comment by randallmeeker** [comment] 2015-05-12 20:31
Yes, that line ```typescript: require('typescript')``` was in one I was testing with. I have updated that example with that line, and still reproduces the error.

**Comment by ivogabe** [comment] 2015-05-12 20:40
@randallmeeker thanks, the message was thrown to often, even when using TS1.5. I've fixed that.

**Comment by randallmeeker** [comment] 2015-05-12 20:47
@ivogabe Thank You! Really appreciate the super quick assistance!

**Closed** 2015-05-16 18:06 UTC

**Comment by jamime** [comment] 2015-05-19 11:47
What is the correct way to use 1.4.1 with the following set up:
````javascript
  src: './src/main/webapp/resources/--js/**/*.ts',
  dest: './src/main/webapp/resources/--js',
````

where `./src/main/webapp/resources/--js/**/*.ts` includes 
`./src/main/webapp/resources/--js/abc/*.ts`
`./src/main/webapp/resources/--js/def/*.ts`

and should compile to 
`./src/main/webapp/resources/--js/abc/*.js`
`./src/main/webapp/resources/--js/def/*.js`

I would like to avoid having to create an empty ts file in `--js` and upgrading to 1.5-beta is not an option for me currently. I can not compile abc and then def separately as `abc `might contain an interface required in `def`.

**Comment by ivogabe** [comment] 2015-05-19 12:04
@jamine You can just keep the gulp file you currently have, as the base directory would be `./src/main/webapp/resources/--js/`, since the glob starts there. That's also the common source directory, so you won't have problems there.

**Comment by jamime** [comment] 2015-05-19 12:09
It currently fails with the following:
> The common source directory of the source files isn't equal to the common base directory of the input files. That isn't supported using the version of TypeScript currently used. Use a newer version of TypeScript instead or have the common source directory point to the common base directory.

`./src/main/webapp/resources/--js/` does not contain any files, just folders such as `controllers`, `models`, `definitions`. Creating an empty `ts` file in `./src/main/webapp/resources/--js/` does fix the issue but I would like to avoid it if at all possible.

````javascript
{
  src: './src/main/webapp/resources/--js/**/*.ts',
  dest: './src/main/webapp/resources/--js',
  options: {
    declarationFiles: false,
    noExternalResolve: true,
    typescript: require('typescript') //1.4.1
  }
}
````

**Comment by ivogabe** [comment] 2015-05-19 12:14
@jamime Can you debug around https://github.com/ivogabe/gulp-typescript/blob/a732052284216827f24b6164c0826145cdff9244/release/compiler.js#L112? Adding `console.log(diff)` would do the job. Could it be that `diff` contains a single slash (`/`)?

**Comment by jamime** [comment] 2015-05-19 12:23
You are correct diff contains `/`.

**Comment by ivogabe** [comment] 2015-05-19 12:25
Ok, I had already a fix for that implemented. You can expect a new release with that fix soon.

**Comment by jamime** [comment] 2015-05-19 12:25
Perfect much appreciated @ivogabe.

**Comment by alex-wilmer** [comment] 2016-06-08 02:51
I've tried all the things in this thread and I can't seem to wrap my head around it..

    node_modules/gulp-typescript/release/output.js:170
        base = file.original.gulp.base;

    TypeError: Cannot read property 'gulp' of undefined

    "gulp-typescript": "2.13.6",

```
gulp.task('ts:compile', function () {
  var f = production ? 'app.min.js' : 'app.js';
  var tsResult = gulp.src('app/**/*.ts')

      .pipe($.typescript(tsProject));

  tsResult.dts.pipe(gulp.dest('dist/dts'));
  tsResult.js.pipe(gulp.dest('.tmp'));

  return tsResult.js
      .pipe($.sourcemaps.init())
      .pipe($.concat(f))
      .pipe($.ngAnnotate())
      .pipe($.if(production, $.uglify()))
      .pipe($.wrap({src: './iife.txt'}))
      .pipe($.sourcemaps.write())
      .pipe(gulp.dest('dist/js'))
      .pipe($.size({title: 'typescript'}));
});
```

**Comment by alex-wilmer** [comment] 2016-06-08 03:23
I'm starting over using the instructions in your README and things are going smoother.. thought I would leave this issue up though in case it's helpful

**Comment by alex-wilmer** [comment] 2016-06-08 04:08
More info.. when I remove `sortOutput: true` the error goes away. Also, I updated "declarationFiles" to be just "declaration"

**Comment by ivogabe** [comment] 2016-06-08 12:45
Does your project work (no runtime errors) if you remove `sortOutput: true`? If not, can you create a new issue and include your project there, as a .zip or with a link?
I do see that using `"module": "commonjs"` doesn't make sense when you also concat your files, so you should remove that line. But I'm afraid that that won't solve your issue.
