### ISSUE TITLE
Setting 'allowJs' and 'declaration' options causes 'emit failed' error

### ISSUE THREAD

**Issue by LPGhatguy** [ivogabe/gulp-typescript#356] opened 2016-05-25 20:57 UTC
This is very close to a continuation of #259.

I have a template project with typings output that has the option to source JS, but doesn't ship with any JS source. As such, `declaration` and `allowJs` are both set to true. This causes an `emit failed` error.

There are some closed issues that talk about this combination, but I'm not expecting typings to output from the JS portion of the code -- I just want everything to process successfully, or at least output with a useful error message!

Here's a repository that reproduces the error with just `gulp`, `gulp-typescript`, and `merge-stream`:

https://github.com/LPGhatguy/gulp-typescript-allowjs-bug

**Comment by ivogabe** [comment] 2016-05-25 21:01
Looks like a duplicate of #317 and Microsoft/TypeScript#7546

**Comment by LPGhatguy** [comment] 2016-05-25 21:22
The behavior described by #317 implies that compilation succeeds, and JS is ignored, which would be okay, but the reply on the TypeScript error talks about there being an error.

**Comment by ivogabe** [comment] 2016-12-11 19:05
Closing this in favour of Microsoft/TypeScript#7546.

**Closed by ivogabe** 2016-12-11 19:05 UTC
