### ISSUE TITLE
Unable to compile typescript using 2.13.5 version

### ISSUE THREAD

**Issue by volzok** [ivogabe/gulp-typescript#362] opened 2016-06-01 06:36 UTC
After updating gulp-typescript to latest version (2.13.5) none of my projects can be built.
I am receiving the following errors:

```
[08:29:48] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
node_modules\gulp-typescript\release\compiler.d.ts (32,22): '=' expected. (1005)
node_modules\gulp-typescript\release\compiler.d.ts (32,22): Cannot find name 'commonBaseDiff'. (2304)
node_modules\gulp-typescript\release\input.d.ts (46,5): Duplicate identifier 'readonly'. (2300)
node_modules\gulp-typescript\release\input.d.ts (46,14): '=' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (46,14): Cannot find name 'commonBasePath'. (2304)
node_modules\gulp-typescript\release\input.d.ts (46,28): ';' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (46,30): Duplicate identifier 'string'. (2300)
node_modules\gulp-typescript\release\input.d.ts (47,5): Duplicate identifier 'readonly'. (2300)
node_modules\gulp-typescript\release\input.d.ts (47,14): '=' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (47,14): Cannot find name 'commonSourceDirectory'. (2304)
node_modules\gulp-typescript\release\input.d.ts (47,35): ';' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (47,37): Duplicate identifier 'string'. (2300)
node_modules\gulp-typescript\release\input.d.ts (65,5): Duplicate identifier 'readonly'. (2300)
node_modules\gulp-typescript\release\input.d.ts (65,14): '=' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (65,14): Cannot find name 'firstSourceFile'. (2304)
node_modules\gulp-typescript\release\input.d.ts (65,29): ';' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (66,5): Duplicate identifier 'readonly'. (2300)
node_modules\gulp-typescript\release\input.d.ts (66,14): '=' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (66,14): Cannot find name 'commonBasePath'. (2304)
node_modules\gulp-typescript\release\input.d.ts (66,28): ';' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (66,30): Duplicate identifier 'string'. (2300)
node_modules\gulp-typescript\release\input.d.ts (67,5): Duplicate identifier 'readonly'. (2300)
node_modules\gulp-typescript\release\input.d.ts (67,14): '=' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (67,14): Cannot find name 'commonSourceDirectory'. (2304)
node_modules\gulp-typescript\release\input.d.ts (67,35): ';' expected. (1005)
node_modules\gulp-typescript\release\input.d.ts (67,37): Duplicate identifier 'string'. (2300)
    at getOutput (c:\Projects\Git\LogicClient\node_modules\ts-node\src\ts-node.ts:210:13)
    at Object.loader (c:\Projects\Git\LogicClient\node_modules\ts-node\src\ts-node.ts:225:23)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (c:\Projects\Git\LogicClient\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (c:\Projects\Git\LogicClient\node_modules\liftoff\index.js:193:16)
    at module.exports (c:\Projects\Git\LogicClient\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (c:\Projects\Git\LogicClient\node_modules\liftoff\index.js:185:9)
```

If I downgrade to version 2.12.x everything compiles without problems.

My tsconfig:

```javascript
{ 
     "compilerOptions": { 
         "emitDecoratorMetadata": true, 
         "experimentalDecorators": true,
         "moduleResolution": "node",
         "module": "commonjs", 
         "target": "es6",
         "sourceMap": true,
         "outDir": "dist",
         "declaration": false,
         "jsx": "react"
     },
     "exclude": [
         "node_modules",
         "dist",
         ".vscode",
         "docs",
         "typings/browser.d.ts",
         "typings/browser",
         "external_modules"
     ]
} 
```
My gulp task:

```typescript
gulp.task('build.js.dev', () => 
{
    var tsProject = ts.createProject('tsconfig.json');
    
    var tsResult = tsProject.src()
        .pipe(sourcemaps.init())   
        .pipe(ts(tsProject));  
        
    return merge([
        //Write definitions 
        //tsResult.dts.pipe(gulp.dest(TEMP_TARGET_FOLDER)),
        //Write compiled js
        tsResult.js.pipe(sourcemaps.write("./", { sourceRoot: __dirname })).pipe(gulp.dest(TEMP_TARGET_FOLDER))]);
});
```

**Comment by ivogabe** [comment] 2016-06-01 11:54
Duplicate of #360

**Closed by ivogabe** 2016-06-01 11:54 UTC
