### ISSUE TITLE
gulp-typescript fails silently, regardless of reporter used

### ISSUE THREAD

**Issue by LukeNZ** [ivogabe/gulp-typescript#374] opened 2016-06-30 20:52 UTC
Using Visual Studio 2015, gulp-typescript provides no output whatsoever when a semantic error exists, except for:

```
[[08:54:09] Starting 'angular:apps'...
[08:54:12] TypeScript: 1 semantic error
[08:54:12] TypeScript: emit failed
[08:54:12] Finished 'angular:apps' after 2.56 s]
```

**Expected behavior:**

On transpilation of a typescript file with errors, show the error. 

**Actual behavior:**

gulp-typescript does not output an error (even using fullReporter).

**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
var app= ts.createProject('./tsconfig.json');
gulp.task('angular:apps', function (done) {

    return gulp.src("Scripts/app/**/*.ts").pipe(ts(app), undefined, ts.reporter.fullReporter())
    .js.pipe(gulp.dest(webroot + 'angular/app/'));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "removeComments": false,
    "sourceMap": false,
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by ivogabe** [comment] 2016-07-01 19:29
Looks like a duplicate of #371

**Closed** 2016-07-13 08:22 UTC
Labels: Duplicate

**Comment by rationalthinker1** [comment] 2020-03-29 22:21
Set  "noEmitOnError": true, to false
