### ISSUE TITLE
No compiled output from gulp-typescript when using outDir

### ISSUE THREAD

**Issue by Roaders** [ivogabe/gulp-typescript#541] opened 2017-09-24 09:06 UTC
**Expected behavior:**
One js file per ts file compiled into specified folder

**Actual behavior:**
no outDir folder created and no js emitted anywhere. No errors thrown

**Your gulpfile:**
```javascript
gulp.task('compile-dev-ts', ['clean'], function () {

	var tsProject = ts.createProject('tsconfig.json');
	
	var tsResult = tsProject.src().pipe(tsProject());

    return tsResult.js.pipe(gulp.dest("./"));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": true,
    "diagnostics": true,
    "outDir": "build/ts"
  },
  "files": [
    "ts/app.ts"
  ]
}

```

I have tried this against `3.2.2`, `3.2.1`, `3.0.2` and all of these seem to have this problem.
`tsc` works fine

Seems to be similar to #348 and #305

**Comment by impworks** [comment] 2017-09-26 08:47
I also have this issue. For me `gulp-typescript` outputs only the index file, while `tsc` emits everything with correct folder structure.

My `tsconfig.json` contains the following:

```
{
    "compilerOptions": {
        "allowJs": false,
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "target": "es5",
        "removeComments": true,
        "noEmitOnError": true,
        "diagnostics": true,
        "module": "amd",
        "moduleResolution": "node",
        "lib": [ "dom", "es5", "es2015.promise" ]
    },
    "include": [
        "source/**/*.ts"
    ]
}
```

The `gulpfile.js` contains:

```
var gulp = require('gulp'),
    tsc = require('gulp-typescript'),
    typescript = tsc.createProject('tsconfig.json');

gulp.task('default', function() {
    return gulp.src(['./source/main.ts'])
               .pipe(typescript())
               .pipe(gulp.dest('./build'));
});
```

Versions: `typescript = 2.5.2`, `gulp-typescript = 3.2.2`.

**Comment by ivogabe** [comment] 2017-10-23 20:15
See #190

**Comment by ivogabe** [comment] 2017-12-23 15:54
Closing as a duplicate of #190

**Closed by ivogabe** 2017-12-23 15:54 UTC
