### ISSUE TITLE
tsconfig extends support

### ISSUE THREAD

**Issue by Peter-Juhasz** [ivogabe/gulp-typescript#467] opened 2016-12-08 19:28 UTC
TypeScript: 2.1.4
Version: 3.1.3

**Expected behavior:**
Applies inheritance and interpolates the tsconfig file references in the extends attribute.

Running `tsc` works as expected.

**Actual behavior:**
createProject does not support tsconfig inheritance, it passes only the tsconfig which references another one without interpolating the base config file.

Even if I change extends to a file which does not even exists, there is no error, just different compiler options than set in the base tsconfig.

**gulpfile.js**
```javascript
var tsBuildProject = typescript.createProject("tsconfig.build.json");
gulp.task("app:scripts:ts:build", function () {
    return tsBuildProject.src()
        .pipe(sourcemaps.init())
        .pipe(tsBuildProject()).js
        .pipe(ngAnnotate())
        .pipe(concat(paths.concatAppJsDest))
        .pipe(uglify())
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("."));
});
```

**tsconfig.json**
```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "target": "ES5"
    }
    ...
}
```

**tsconfig.build.json**
```json
{
    "extends": "./tsconfig",
    ...
}
```

**Comment by ivogabe** [comment] 2016-12-11 18:40
Duplicate of #459

**Closed by ivogabe** 2016-12-11 18:40 UTC
