### ISSUE TITLE
External node_modules arn't compiled

### ISSUE THREAD

**Issue by fredrikbonander** [ivogabe/gulp-typescript#352] opened 2016-05-19 21:14 UTC
Don't know if this is by design or not. We use internal npm packages that are linked with `npm link`. When compiling the project with `tsc` the internal modules are compiled and outputted correctly, but with `gulp-typescript` they are excluded.

**Expected behavior:** Compiling imported `node_modules` that are typescript

**Actual behavior:** Seems like `ts()` is ignoring/exluding them

**gulpfile:**
```javascript
var tsProject = ts.createProject(appConfig.typescript.config),
                result = tsProject.src()
                    .pipe(sourcemaps.init())
                    .pipe(ts(tsProject));

            return result.js
                .pipe(sourcemaps.write())
                .pipe(gulp.dest(appConfig.output));
````
**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "../build/"
  },
  "exclude": [
    "node_modules",
    "typings/globals",
    "typings/index.d.ts"
  ]
}
```

**Comment by ivogabe** [comment] 2016-05-23 15:58
Duplicate of #190?

**Comment by fredrikbonander** [comment] 2016-05-30 06:03
@ivogabe yes.

**Closed** 2016-05-30 06:03 UTC
