### ISSUE TITLE
Problems after upgrading from 2.6.0

### ISSUE THREAD

**Issue by centi** [ivogabe/gulp-typescript#115] opened 2015-05-11 15:40 UTC
I have issues with my typescript part of gulpfile after upgrading `gulp-typescript` module from version `2.6.0` to `2.7.3`. I tried all versions from `2.7.0` and up and it seems the problem exists since `2.7.0`. Nothing except the `gulp-typescript` version changed in my project.

When I run this gulp task for typescript:

```javascript
gulp.task('typescript', function () {
	var res = gulp.src('path/to/typescript/**/*.ts')
		.pipe(ts({declarationFiles : false}));

	res.js.pipe(gulp.dest('path/to/resources/'));
});
```

it ends with this error:

```
PATH_TO_PROJECT\node_modules\gulp-typescript\release\output.js:59
					file.skipPush = !file.original.gulp;
												  ^
TypeError: Cannot read property 'gulp' of undefined
	at Output.addOrMergeFile (PATH_TO_PROJECT\node_modules\gulp-typescript\release\output.js:59:51)
	at Output.write (PATH_TO_PROJECT\node_modules\gulp-typescript\release\output.js:35:14)
	at ProjectCompiler.inputDone (PATH_TO_PROJECT\node_modules\gulp-typescript\release\compiler.js:58:33)
	at CompileStream.end (PATH_TO_PROJECT\node_modules\gulp-typescript\release\main.js:52:31)
	at DestroyableTransform.onend (PATH_TO_PROJECT\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\
_stream_readable.js:523:10)
	at DestroyableTransform.g (events.js:180:16)
	at DestroyableTransform.emit (events.js:117:20)
	at PATH_TO_PROJECT\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
	at process._tickCallback (node.js:419:13)
```

Can you help to locate the issue?

**Comment by ivogabe** [comment] 2015-05-11 15:52
Can you post your project or a minimal example that reproduces this problem? Also, what happens when you add the `noExternalResolve: true` option?

**Comment by centi** [comment] 2015-05-11 16:08
When I add the `noExternalResolve: true` option it ends up with this kind of error (all paths are correct):

```
SRC\MY_PROJECT\my_file.ts(1,1): 6053 File 'SRC/TYPES/angular.d.ts' not found.
```

At the beginning of the `my_file.ts` is this declaration:

```
/// <reference path="../types/angular.d.ts" />
```

**Comment by centi** [comment] 2015-05-11 16:31
I can't post the actual project and right now I can't reproduce the problem in a minimalist example. But I will keep trying :)

**Comment by ivogabe** [comment] 2015-05-11 18:21
This looks a lot like #112 which has been fixed in v2.7.3.

For the example code, you'll have to replicate the file structure and the references and import between the files. Besides that, it might be worth to debug the method `commonBaseDiff` (in `node_modules/gulp-typescript/release/output.js`), the return value and the values of `expected` and `real` might be interesting.

**Comment by ivogabe** [comment] 2015-05-12 11:03
This might be fixed with #117, can you test it using the master from GitHub?

**Comment by centi** [comment] 2015-05-12 11:35
Unfortunately, neither #112 or #117 does fix my problem. I managed to prepare a minimal project structure, which gives me the error. You can get it here: https://dl.dropboxusercontent.com/u/8744375/GulpTypescriptError.zip

It is quite possible, that I'm just missing something, or doing something wrong, because I'm new to Gulp.

**Comment by centi** [comment] 2015-05-12 11:36
I tried my example both on Windows (node v0.10.33) and Linux (node v0.10.26).

**Comment by ivogabe** [comment] 2015-05-12 11:54
Found it, it's because the common source directory (the directory that contains all files, in this case `lorem/typescript/display`), calculated by TypeScript is a subdirectory of the provided base path (where the glob starts in the `gulp.src` call, `lorem/typescript`). TypeScript 1.5 introduces a new option to provide the common directory (rootDir). gulp-typescript automatically sets that setting, but it doesn't work for TS1.4. There are various ways to fix it:

1. Use `gulp.src('lorem/typescript/display/**/*.ts')`
2. Use version 1.5 of TypeScript (see readme of gulp-typescript)
3. Add a source file under `lorem/typescript`

**Closed by ivogabe** 2015-05-12 11:54 UTC

**Comment by centi** [comment] 2015-05-12 13:10
Great! Thanks for the tips. I can't use the first suggestion, but the others look good.
