### ISSUE TITLE
TSC errors don't make gulp build fail

### ISSUE THREAD

**Issue by ulrichb** [ivogabe/gulp-typescript#469] opened 2016-12-11 15:21 UTC
Errors are ignored (even with `--noEmitOnError`).

**Expected behavior:**
* Extract [GulpTypeScriptErrorRepro.zip](https://github.com/ivogabe/gulp-typescript/files/644519/GulpTypeScriptErrorRepro.zip)
* `npm installl`
* `node_modules/.bin/gulp && echo == success ==`
* Exit code <> 0 (no "== success ==" output)

**Actual behavior:**
* Exit code == 0 ("== success ==" output)

Same on Windows/node v7.2.1; Ubuntu/node v0.10.25.

**Your gulpfile:**
```javascript
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('build', function () {
    return gulp.src('*.ts')
        .pipe(ts({
            //noEmitOnError: true,
            out: 'out.js'
        }))
        .pipe(gulp.dest('.'));
});

gulp.task('default', ['build']);
```
**Code**
```typescript
class C {}

error_line
```

**Comment by ivogabe** [comment] 2016-12-11 18:41
Duplicate of #295

**Closed by ivogabe** 2016-12-11 18:41 UTC
