### ISSUE TITLE
Declaration files not generated with inherited tsconfig.json

### ISSUE THREAD

**Issue by yahiko00** [ivogabe/gulp-typescript#520] opened 2017-07-04 09:01 UTC
When the _tsconfig.json_ directly used by the TypeScript project does not explicitly set `declaration` to `true`, even if its parent does, then gulp-typescript does not generate declaration files, unlike the inline compiler `tsc`.

I use gulp-typescript version 3.1.7 and TypeScript 2.4.1.

Here is the _gulpfile.js_:

    const tsProject = ts.createProject(config);
    const tsResult = tsProject.src()
        .pipe(sourcemaps.init())
        .pipe(tsProject());

    return merge([
        tsResult.js
            .pipe(sourcemaps.write())
            .pipe(gulp.dest(dest)),
        tsResult.dts
            .pipe(rename("index.d.ts"))
            .pipe(gulp.dest(dest))])
        .on("error", gutil.log);

Above, the parameter `config` in the `createProject()` method refers to the following _tsconfig.debug.json_:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "removeComments": false
  }
}
```

Here is its parent, _tsconfig.json_:
```
{
  "include": [ "./src/**/*.ts" ],
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */

    "declaration": true,                      /* Generates corresponding '.d.ts' file. */

    "removeComments": true,                   /* Do not emit comments to output. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "noUnusedLocals": true,                   /* Report errors on unused locals. */
    "noUnusedParameters": true,               /* Report errors on unused parameters. */
    "noImplicitReturns": true,                /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true        /* Report errors for fallthrough cases in switch statement. */
  }
}
```

To solve this issue, we need to explicitely set `declaration` to `true` in the `createProject()` method, or repeat `"declaration": true` in the inherited _tsconfig.json_ (here, _tsconfig.debug.json_).

This issue refers to this one: https://github.com/ivogabe/gulp-typescript/issues/231

**Comment by ivogabe** [comment] 2017-07-06 20:52
Duplicate of #459, will be part of a new release soon

**Closed by ivogabe** 2017-07-06 20:52 UTC
