### ISSUE TITLE
Task never finishs with outDir in 2.7.4

### ISSUE THREAD

**Issue by arnaudpourbaix** [ivogabe/gulp-typescript#128] opened 2015-05-19 10:18 UTC
Hello,

I'm now using 2.7.4 version with outDir options. Here is my config:
```
    var tsProject = typescript.createProject({
        noImplicitAny: config.build.no_implicit_any,
        declarationFiles: true,
        noExternalResolve: false,
        target: 'ES5',
        sortOutput: true,
        outDir: config.local.typescript_declarations_folder
    });
```

When I run my typescript task, it never finishs. I must hit control-c to kill it.
My declaration files is generated with good relative paths, thanks to outDir option. But my js is not generated (probably waiting for something ?)

If I disable outDir, everything works except of course my relative paths in declarations.

**Comment by ivogabe** [comment] 2015-05-19 10:50
Can you post more about your project?

**Comment by arnaudpourbaix** [comment] 2015-05-19 11:15
Here is my typescript task (I removed a lot of things to make it clear).
This code works fine without outDir:

```
    gulp.task('ts2', [], function () {
        var tsResult = gulp.src(config.app_files.ts.globs).pipe(typescript(tsProject));

        return merge([
            tsResult.dts
                .pipe(concat(config.app_files.ts.output_typescript_declaration_filename))
                .pipe(gulp.dest(config.build.target_folder)),

            streamqueue({ objectMode: true },
                tsResult.js,
                getTemplateStream())
                .pipe(gulp.dest('.'))
                .pipe(concat(config.app_files.ts.output_javascript_filename))
                .pipe(gulp.dest(config.build.target_folder))
        ]);
    });
```

**Comment by ivogabe** [comment] 2015-05-19 12:24
I can't reproduce it using your example. Can you check whether you are using the latest versions of all plugins? If that doesn't solve it, can you post a full example including source files that reproduces your problem?

**Comment by arnaudpourbaix** [comment] 2015-05-19 14:24
I will try to update my modules and see if it works better.
Here is my current deps:
```
    "del": "1.1.1",
    "event-stream": "3.3.0",
    "fs": "0.0.2",
    "gulp": "3.8.11",
    "gulp-angular-templatecache": "1.5.0",
    "gulp-check-file-naming-convention": "0.0.2",
    "gulp-chmod": "1.2.0",
    "gulp-clean-ts-extends": "0.1.1",
    "gulp-concat": "2.4.3",
    "gulp-connect": "2.2.0",
    "gulp-csslint": "0.1.5",
    "gulp-htmlhint": "0.0.9",
    "gulp-jscs-custom": "0.1.3",
    "gulp-jshint": "1.9.4",
    "gulp-karma": "0.0.4",
    "gulp-less": "3.0.2",
    "gulp-minify-css": "1.0.0",
    "gulp-minify-html": "1.0.0",
    "gulp-ng-annotate": "0.5.2",
    "gulp-plumber": "1.0.0",
    "gulp-recess": "1.1.1",
    "gulp-remote-src": "0.3.0",
    "gulp-replace": "0.5.2",
    "gulp-tar": "1.3.2",
    "gulp-tslint": "1.4.4",
    "gulp-typescript": "2.7.4",
    "gulp-uglify": "1.1.0",
    "gulp-util": "3.0.4",
    "gulp-watch-less": "1.0.1",
    "jasmine-core": "2.1.3",
    "jshint-stylish": "1.0.1",
    "karma-chrome-launcher": "0.1.7",
    "karma-coverage": "0.2.7",
    "karma-firefox-launcher": "0.1.4",
    "karma-ie-launcher": "0.1.5",
    "karma-jasmine": "0.3.4",
    "karma-junit-reporter": "0.2.2",
    "karma-phantomjs-launcher": "0.1.4",
    "karma-qunit": "0.1.4",
    "karma-typescript-preprocessor": "0.0.15",
    "merge2": "0.3.1",
    "qunitjs": "1.17.1",
    "run-sequence": "1.0.2",
    "streamqueue": "0.1.3",
    "typescript": "1.4.1"
```

**Comment by ivogabe** [comment] 2015-05-24 17:18
Did updating the dependencies fix it?

**Comment by arnaudpourbaix** [comment] 2015-05-25 07:31
I haven't tried yet, but my coworker told me he also had problems with 2.7.4 and he successfully switched to 2.7.5 (which was not available at the moment I checked).
I will test it this week, but I have other prioritized tasks to do before.

**Comment by arnaudpourbaix** [comment] 2015-05-28 09:58
I made some tests this morning and I confirm it doesn't work better no matter what I do.
Updating to latest version didn't help at all.

As soon as I set outDir, my task never ends and I found out that this line blocks process:
```
.pipe(BuildConfig.gulp.dest("."))
```

So, gulp-typescript is not directly causing any process block. But there is something in the output stream that does (I assume this).
Strangely, outDir only affect declaration stream but my problem is for javascript output stream !

I can't really explain this situation and I will try to find more stuff.

**Comment by ivogabe** [comment] 2015-08-01 14:31
I've taken another look at it, and I still couldn't reproduce it. I have also tried using the versions you listed above. Can you again try to update gulp, gulp-typescript & merge2? If that doesn't solve your problem, can you create a small example that can reproduce it and upload that example to GitHub?

**Comment by ivogabe** [comment] 2015-08-27 09:19
Any updates?

**Comment by ivogabe** [comment] 2015-09-07 05:27
@arnaudpourbaix Have you had time to investigate this? Or have you already solved it yourself? I'm closing this for now, if you have a reproduction I'll reopen this.

**Closed by ivogabe** 2015-09-07 05:27 UTC
Labels: Bug, Needs More Info
