### ISSUE TITLE
file names in source maps are set to all lowercase

### ISSUE THREAD

**Issue by benjaminRomano** [ivogabe/gulp-typescript#255] opened 2015-12-20 03:13 UTC
The file names in the source map's source property are being set to all lowercase.

For example, `['exampleFileName.ts']` is being changed to `['examplefilename.ts']`.

I'm currently using Visual Studio Code's debugger and my source maps aren't work because the debugger expects the file names to have the correct casing.

I was able to fix the problem locally by removing the call to toLowerCase in the normalizePath function in utils.ts. Is there a reason why the file names are lowercase or would it be fine to change that?

**Comment by ivogabe** [comment] 2015-12-21 18:33
Thanks for reporting, I will take a look at this. The `toLowerCase` is necessary, for case insensitive file systems. The result of normalizePath should not be propagated to the source map though.

**Comment by mtebenev** [comment] 2015-12-31 00:11
I confirm the issue. Also it's strange that on some modules the names are ok (i.e. not lowered).

**Comment by benjaminRomano** [comment] 2016-01-29 04:15
Any update on this? This is a big problem when using visual studio code.

**Comment by pyrho** [comment] 2016-02-01 13:37
I confirm the issue, prevents from debugging with VSCode.
I also confirm the workaround proposed by @benjaminRomano .

> The toLowerCase is necessary, for case insensitive file systems
Not sure I understand why this is required for case insensitive FS, since they are.... case insensitive.
Maybe we could just get rid of that bit entirely.

**Comment by ivogabe** [comment] 2016-02-02 10:34
> Not sure I understand why this is required for case insensitive FS, since they are.... case insensitive.
Maybe we could just get rid of that bit entirely.

If the compiler has already seen `foo.ts`, and `Foo.ts` is referenced from some other file, it should not try to fetch `Foo.ts` (which would resolve to the same content of `foo.ts`). The same file would be compiled twice this way, which can give errors that an identifier has already been imported. This normalized path should only be used internal and not be exposed however.

**Comment by pyrho** [comment] 2016-02-02 14:18
Right, thanks for the reply.
Any pointers on how this should be fixed ? Maybe I can come up with a PR.

**Comment by ivogabe** [comment] 2016-02-02 16:35
I'm not entirely sure, but it's probably `lib/output.ts` or `lib/compiler.ts`.

**Comment by mbakturk** [comment] 2016-02-14 18:00
I encountered same problem, all files are mapped as lower case name

**Comment by holdfenytolvaj** [comment] 2016-02-23 05:02
> If the compiler has already seen foo.ts, and Foo.ts is referenced from some other file, it should not try to fetch Foo.ts
Not sure whether it is a good feature, since if somebody deploy his/her code from mac/win to linux server, it can cause issues. It is better to detect issues as early as possible, would be preferable to throw an error.

**Comment by ivogabe** [comment] 2016-02-23 07:06
@holdfenytolvaj What I described matches the behavior of `tsc`.

**Comment by holdfenytolvaj** [comment] 2016-02-23 07:16
@ivogabe strange, would be interesting to know why... Since it is hiding errors, that could be revealed at compile time instead of runtime. One of the biggest advertisement of js the code portability is hurt by this.

**Comment by ivogabe** [comment] 2016-02-23 19:53
@holdfenytolvaj You can use `forceConsistentCasingInFileNames` to catch those issues. See the [wiki](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options) for more details.

**Comment by jwbay** [comment] 2016-02-28 05:29
I'm seeing this as well, and managed to get a minimal failing test case at https://github.com/jwbay/gulp-typescript/tree/sourcemap-casing/test/sourceMaps

I had a hard time reproducing on a smaller scale than my actual project, but from what I managed to find, this bug surfaces when you reference files by import in a directory higher than the target tsconfig.json. Definition files resolved via triple slash references don't seem to trigger it.

**Comment by jwbay** [comment] 2016-02-28 23:48
Found the culprit, fix looks like this: https://github.com/jwbay/gulp-typescript/compare/windows-tests...jwbay:sourcemaps?expand=1

From what I could tell there's no reason to lowercase any paths in that block, but I just made the minimal change to fix the bug.

The fix branch (and its test baselines) are built off #294. I can follow up with a PR if/once that is merged, or someone with a mac/linux box can target something similar against master.

**Comment by ivogabe** [comment] 2016-02-29 08:17
@jwbay The call to `toLowerCase` is important here. The real issue is that a normalized path is shown to the user, whereas these should always stay internal.

**Comment by jwbay** [comment] 2016-03-01 01:16
Oooh, for `path.relative` to work? Could just as easily create a local that's not lowercased and substring into that for the return, the lengths will stick check out. I actually did that first, then wondered why I making a new string...

**Closed** 2016-03-01 06:58 UTC
Labels: Bug
