### ISSUE TITLE
Support to baseUrl props in tsconfig

### ISSUE THREAD

**Issue by greatelv** [ivogabe/gulp-typescript#475] opened 2017-01-03 07:38 UTC
I got a issue about baseUrl, module resolutions mapping.
As i used native tsc compiler, Build worked well. but, 
Using gulp-typescript emit error message about module resolutions.
Is possible using baseUrl props on gulp-typescript ? 

My env :
gulp-typescript: 3.1.3
typescript: 2.1.4

**Your gulpfile:**
```javascript
var tsProject = ts.createProject(tsconfig);
context.tsProject = tsProject;

function build() {
  var tsResult = gulp.src([config.paths.src.scripts.ts, config.paths.src.scripts.typings])
    .pipe(gulpif(!release, sourcemaps.init()))
    .pipe(tsProject())
    .on('error', handleError);
  tsResult.dts
    .pipe(gulp.dest(config.paths.src.scripts.tmp + '/d', {mode: '0644'}));

  return tsResult.js
    .pipe(cache('tsapp'))
    .pipe(ngAnnotate({ map: false }))
    .pipe(gulpif(!release, sourcemaps.write()))
    .pipe(gulp.dest(config.paths.src.scripts.tmp + '/js', {mode: '0644'}));
}

build();
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "declaration": true,
    "noImplicitAny": false,
    "noEmitOnError": false,
    "sourceMap": true,
    "module": "commonjs",
    "target": "ES5",
    "jsx": "react",
    "outDir": "../../.tmp",
    "lib": ["dom", "es2015.promise", "es5"],
    "baseUrl": ".",
    "paths": {
      "components" : ["./components"]
    }
  },
  "filesGlob": [
    "./**/*",
    "../typings/**/*.*",
    "!../../node_modules/@types/**/*.*"
  ],
  "include": [
    "./**/*.ts",
    "./**/*.tsx",
    "../typings/**/*.ts"
  ],
  "exclude": [
    "../../node_modules",
    "../../bower_components"
  ]
}
```

I'd like to use absolute path instead of relative path. 
(example)
```javascript
import { store } from '../../components/react/util';
to
import { store } from 'components/react/util';
```

**Comment by ivogabe** [comment] 2017-01-06 14:55
Can you replace `gulp.src(..)` with `tsProject.src()`? Then you should see the same behaviour of `tsc`. I suspect that `gulp.src` gives a different base path (which is inferred as the place where the glob starts).

**Comment by ZoserLock** [comment] 2017-08-06 07:32
I am having a similar issue.

Using tsc directly the project build without problems but when using gulp the modules are not found.

```Error: Cannot find module 'utils'```

My env :
gulp-typescript@3.2.1
typescript@2.4.2

tsconfig.json
```json
{
    "compilerOptions": 
    {
        "removeComments": true,
        "noImplicitAny": true,
        "target": "ES5",
        "baseUrl": "./src"
    },
    "include": [
    "./src/**/*.ts"
    ]
}
```
gulpfile.js
```
...
gulp.task('build',['clean'], function () 
{
    return tsProject.src()
    .pipe(tsProject())
    .pipe(gulp.dest('build/'))
});
...
```

**Comment by kashinross** [comment] 2017-08-21 23:42
I'm having a similar issue using `baseUrl` and `paths` in my tsconfig.json file.

gulp-typescript@3.2.1
typescript@2.0.10

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "outDir": "build",
    "suppressImplicitAnyIndexErrors": true,
    "allowJs": true,
    "noUnusedLocals": true,
    "paths": {
      "twilight-automation": ["source"],
      "twilight-automation/*": ["source/*"]
    },
    "typeRoots": [
        "./node_modules/@types"
    ]
  },
  "filesGlob": [
    "source/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "build"
  ]
}
```

gulpfile.js
```
var gulp = require('gulp');
var ts = require('gulp-typescript');

var tsProject = ts.createProject('tsconfig.json');

gulp.task('build', function() {
    var tsResult = tsProject.src().pipe(tsProject());
    return tsResult.js.pipe(gulp.dest('build'));
});

gulp.task('default', ['build']);
```

**Comment by arielweinberger** [comment] 2017-08-24 01:00
Experiencing the same thing. Defining a baseUrl and importing modules in my typescript files will not work. After compilation with gulp-typescript the path is invalid.

**Comment by greatelv** [comment] 2017-08-24 02:40
In my case, My issue is not relate to gulp-typescript.
That is caused by module-bundler (Browserify) !!
The gulp-typescirpt support baseUrl props well.

**Comment by sudomaxime** [comment] 2017-09-05 02:00
I'm having the same issue, everything works well with tsc command (typescript compiler), when I run the compiler I get no error messages, however when my server starts I get the ```Error: Cannot find module 'src/tools/logger'```

**Comment by ivogabe** [comment] 2017-09-20 15:53
Please remember that this path-mapping is will not affect the paths in the generated JavaScript code. So you need to make sure yourself that these paths work at runtime. You'll probably need to configure Browserify, Webpack or some other bundler to consider this.

If you're having issues where gulp-typescript throws an error that it cannot find some module, please create a minimal reproduction. Such a reproduction should compile fine with `tsc`, but fail with gulp-typescript. If you've got such reproduction, you can share it here.

**Comment by ivogabe** [comment] 2017-12-23 15:58
> If you're having issues where gulp-typescript throws an error that it cannot find some module, please create a minimal reproduction. Such a reproduction should compile fine with tsc, but fail with gulp-typescript. If you've got such reproduction, you can share it here.

Closing this as there is still no standalone reproduction. If you have one, please share it here and I'll reopen.

@sudomaxime Since you described that tsc and gulp-typescript behave differently on your code base, you might have a reproduction? Could you share it?

**Closed by ivogabe** 2017-12-23 15:58 UTC
